### ISSUE TITLE
Logic for more than 10-15 pages

### ISSUE THREAD

**Issue by oflittlemother** [sbaidon/vue-paginatron#2]
This is a very good component but it lacks the logic to handle lots of pages.
For example, something like this:

```[1] ... [98] [99] [100*] [101] [102] ... [221]```

Currently, it just creates a huge grid listing of all pages when testing on 2000+ items.

**Comment by sbaidon** [comment]
If I am not wrong you could implement a `skip` method on the consumer component and then just loop over whatever pages are left.

Something like this

```html
<div v-for="(page, index) in skip(pages, 10)" :key="index">
    <p @click="setPage(index)">{{ page }}</p>
</div>
```
