### ISSUE TITLE
Error: # of Items per page is higher

### ISSUE THREAD

**Issue by stefanwuthrich** [sbaidon/vue-paginatron#6]
Cool component, but I have a little problem.
Using code below, I get following error:

[Vue warn]: Error in beforeMount hook: Error: # of Items per page is higher than the items length
found in
---> <Paginatron>
       <Blog> at src/views/Blog.vue
         <App> at src/App.vue
           <Root>

Here my code (works fine without pagination):

`            <template>
            <div class="container">
                <vue-headful
                description="Interesting Links, Libraries and News for Full-Stack Developers"
                title="Full-Stack Developer Blog"
                />

        <div class="row">
            <div class="col-12">
                <h2 class="display-4">Full-Stack Blog</h2>
                <p class="blog">Links, Libraries and News for Full-Stack Developers</p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-8">
                <paginatron @change="updateItems" @next="advanced" @previous="decreased" :items-per-page="5" :items="posts">
                    <div slot-scope="{ setPage, nextPage, prevPage, page, pages, hasNextPage, hasPrevPage, nextButtonEvents, prevButtonEvents, nextButtonAttrs, prevButtonAttrs }">
                        <button v-on="prevButtonEvents" v-bind="prevButtonAttrs" >Prev</button>
                        <article :key="post.id" class="blog-post" v-for="post in activeItems">
                            <BlogPostDetail :post="post" mode="List"/>
                        </article>
                        <button v-on="nextButtonEvents" >Next</button>
                        <div v-for="(page, index) in pages" :key="index">
                            <span @click="setPage(index)">{{ page }}</span>
                        </div>

                    </div>
                </paginatron>
            </div>
            <div class="col-md-4">
                <b-card-header>Full-Stack Jobs:
                    <b-link class="blog" to="/">See Job List</b-link>
                </b-card-header>
                <b-dd-divider></b-dd-divider>
                <b-card-header>Submit Job:
                    <b-link class="blog" to="/submitjob">Free Job Submission</b-link>
                </b-card-header>
                <b-dd-divider></b-dd-divider>
                <b-card-header>Partner Blog:
                    <b-link class="blog" href="https://golang.ch" target="_blank">Golang News and Libraries</b-link>
                </b-card-header>
                
            </div>

        </div>

            </div>
            </template>
`

`            <script>
                import axios from "axios";
                import {Email, Facebook, Linkedin, Reddit, Twitter, WhatsApp} from 'vue-socialmedia-share';
                import BlogPostDetail from "../components/BlogPostDetail";
                import Paginatron from 'vue-paginatron';
       

    export default {
        name: 'Blog',
        components: {
            //JobSmallList,
            BlogPostDetail,
            Paginatron
        },
        data() {
            return {
                posts: [],
                activeItems: [],
            }
        },
        methods: {
            getPosts: function () {
                axios.get(process.env.VUE_APP_APIBASEURL + "/v1/app/blog/post", {})
                    .then((response) => {
                        this.loading = false;
                        this.posts = response.data.posts;
                    }, (error) => {
                        this.loading = false;
                    });

            },
            updateItems(activeItems) {
                this.activeItems = activeItems;
            },
            decreased({ prev, current }) {
                console.log(prev, current);
            },
            advanced({ activeItems, prev, current }) {
                console.log(prev, current);
            },
            getPostUrl(id, title) {
                let url = '/blog/' + id + '/' + encodeURIComponent(title);
                return encodeURI(url)
            },
            getPostUrlShare(id, title) {
                let url = 'https://fullstackjob.com/blog/' + id + '/' + encodeURIComponent(title);
                return encodeURI(url)
            },
        },
        beforeMount() {
            this.getPosts()
        },
    }
            </script>`

**Comment by sbaidon** [comment]
I could be wrong but I think the problem is that you are setting `items-per-page` as `5`, the problem is that the `posts` array initial value is `[]` , that is why the error is being thrown. 

I would suggest setting a data variable `itemsPerPage` as `0` and then changing it to `5` after you fill the posts array

**Comment by stefanwuthrich** [comment]
makes as much sense as it fix. Shame on me... 
Thanks @sbaidon
